use super::{Addr, Reg, u4};

#[derive(Clone, Copy, Debug)]
pub(crate) enum Ins {
    Op0NNN(Addr),
    Op00E0,
    Op00EE,
    Op1NNN(Addr),
    Op2NNN(Addr),
    Op3XNN(Reg, u8),
    Op4XNN(Reg, u8),
    Op5XY0(Reg, Reg),
    Op6XNN(Reg, u8),
    Op7XNN(Reg, u8),
    Op8XY0(Reg, Reg),
    Op8XY1(Reg, Reg),
    Op8XY2(Reg, Reg),
    Op8XY3(Reg, Reg),
    Op8XY4(Reg, Reg),
    Op8XY5(Reg, Reg),
    Op8XY6(Reg),
    Op8XY7(Reg, Reg),
    Op8XYE(Reg),
    Op9XY0(Reg, Reg),
    OpANNN(Addr),
    OpBNNN(Addr),
    OpCXNN(Reg, u8),
    OpDXYN(Reg, Reg, u4),
    OpEX9E(Reg),
    OpEXA1(Reg),
    OpFX07(Reg),
    OpFX0A(Reg),
    OpFX15(Reg),
    OpFX18(Reg),
    OpFX1E(Reg),
    OpFX29(Reg),
    OpFX33(Reg),
    OpFX55(Reg),
    OpFX65(Reg),
}